[design]
name = "zipdiv"
top = "zipdiv"
rtl = ["src/zipdiv.v"]
clock_port = "i_clk"
frequency_mhz = 50.0

[pdk]
name = "ics55"
root = ""

[flow]
preset = "rtl2gds"
run = "default"

[params.floorplan]
core_util = 0.40

[params.synth]
max_fanout = 6
