[design]
name = "usb"
top = "usb"
rtl = ["src/usb2p0_core.v"]
clock_port = "clk_48"
frequency_mhz = 66.6666666667

[pdk]
name = "ics55"
root = ""

[flow]
preset = "rtl2gds"

[params.floorplan]
core_util = 0.40

[params.cts]
max_fanout = 6
